# Generated by Django 4.2.4 on 2023-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameBook', models.CharField(max_length=200)),
                ('authorBook', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=10)),
                ('editoraBook', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('categoria', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.CharField(max_length=255)),
                ('pdf', models.FileField(default='emprestimos.pdf', upload_to='borrowing_pdfs')),
                ('email', models.EmailField(max_length=299)),
            ],
        ),
    ]
