# Generated by Django 4.2.4 on 2023-11-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookregister',
            name='authorBook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookregister',
            name='descrição',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookregister',
            name='editoraBook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowingdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
