# Generated by Django 4.2.4 on 2023-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_biblioteca', '0002_alter_bookregister_authorbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
