# Generated by Django 4.2.4 on 2023-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_biblioteca', '0003_alter_borrowingdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingdata',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
