# Generated by Django 4.2.4 on 2023-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_biblioteca', '0004_alter_borrowingdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
