# Generated by Django 4.2.4 on 2023-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_biblioteca', '0005_alter_bookregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
